# Generated by Django 3.2.5 on 2021-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restShop', '0002_basemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='type',
            name='characteristics',
            field=models.TextField(blank=True),
        ),
    ]
