# Generated by Django 3.2.5 on 2021-07-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restShop', '0003_auto_20210715_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
